---
title: ""
params:
  status_filtro: NULL
  titulo: NULL
  projetos: NULL
  materiais: NULL
---


```{r setup, include=FALSE}
# library(dplyr)
# library(knitr)

projetos_filtrados <- params$projetos
materiais <- params$materiais
```


```{r, echo=FALSE, results='asis'}
cat("\\vspace*{-1cm}")
cat("\\begin{center}")
cat("\\large\\bfseries ", params$titulo)
cat("\\end{center}")
cat("\\vspace{1cm}")



if(nrow(projetos_filtrados) == 0){

  cat("\\textit{Nenhum projeto encontrado.}")

} else {

  for(i in 1:nrow(projetos_filtrados)){

    projeto <- projetos_filtrados[i,]

    cat("\\newpage")
    cat("\\section*{", projeto$nome, "}")
    cat("\\addcontentsline{toc}{section}{", projeto$nome, "}")
    cat("\\vspace{0.5cm}")

    cat("\\textbf{ID:} ", projeto$id_projeto, "\\\\")
    cat("\\textbf{Status:} ", projeto$status, "\\\\[0.5cm]")

    if(!is.na(projeto$etapa)){
      cat("\\textbf{Etapa:} ", projeto$etapa, "\\\\[0.5cm]")
    }

    if(!is.na(projeto$objetivo)){
      cat("\\textbf{Objetivo}\\\\")
      cat(projeto$objetivo, "\\\\[0.8cm]")
    }

    if(!is.na(projeto$planejamento)){
      cat("\\textbf{Planejamento}\\\\")
      cat(projeto$planejamento, "\\\\[0.8cm]")
    }

    materiais_projeto <- materiais |>
      filter(id_projeto == projeto$id_projeto)

    if(nrow(materiais_projeto) > 0){

      cat("\\textbf{Materiais utilizados}\\\\[0.4cm]")

      print(
        kable(
          materiais_projeto |>
            select(tipo_material,
                   descricao,
                   metragem_utilizada,
                   fio_utilizado),
          format = "latex",
          booktabs = TRUE
        )
      )

      cat("\\vspace{0.8cm}")
    }

    if(!is.na(projeto$ajustes)){
      cat("\\textbf{Ajustes}\\\\")
      cat(projeto$ajustes, "\\\\[0.8cm]")
    }

    if(!is.na(projeto$avaliacao)){
      cat("\\textbf{Avaliação}\\\\")
      cat(projeto$avaliacao, "\\\\[0.8cm]")
    }
  }
}

```


