---
title: ""
output: bookdown::pdf_document2
geometry: top=1cm,bottom=1.2cm,left=1.2cm,right=1.2cm
header-includes:
  - \usepackage{dashrule}
---

\vspace*{-0.8cm}

\begin{center}
\normalsize\bfseries IDENTIFICAÇÃO DE MOLDE
\end{center}

\vspace{1cm}

\begin{center}
\setlength{\tabcolsep}{24pt}
\renewcommand{\arraystretch}{1.2}
\begin{tabular}{cc}

\begin{minipage}[t]{0.43\textwidth}
\normalsize

\textbf{ID do Molde:} \rule{4cm}{0.5pt}

\vspace{0.4cm}

Tipo: \rule{5cm}{0.4pt}

Base utilizada: \rule{4cm}{0.4pt}

Data de criação: \rule{3cm}{0.4pt}

Tamanho / Medidas base: \rule{4cm}{0.4pt}

\vspace{0.4cm}

\textbf{Observações técnicas}

\rule{\textwidth}{0.4pt}

\rule{\textwidth}{0.4pt}

\rule{\textwidth}{0.4pt}

\end{minipage}
&
\begin{minipage}[t]{0.43\textwidth}
\normalsize

\textbf{ID do Molde:} \rule{4cm}{0.5pt}

\vspace{0.4cm}

Tipo: \rule{5cm}{0.4pt}

Base utilizada: \rule{4cm}{0.4pt}

Data de criação: \rule{3cm}{0.4pt}

Tamanho / Medidas base: \rule{4cm}{0.4pt}

\vspace{0.4cm}

\textbf{Observações técnicas}

\rule{\textwidth}{0.4pt}

\rule{\textwidth}{0.4pt}

\rule{\textwidth}{0.4pt}

\end{minipage}

\end{tabular}
\end{center}

\vspace{0.6cm}

\hdashrule{\textwidth}{0.5pt}{3mm 2mm}

\vspace{0.8cm}

\begin{center}
\setlength{\tabcolsep}{24pt}
\renewcommand{\arraystretch}{1.2}
\begin{tabular}{cc}

\begin{minipage}[t]{0.43\textwidth}
\normalsize

\textbf{ID do Molde:} \rule{4cm}{0.5pt}

\vspace{0.4cm}

Tipo: \rule{5cm}{0.4pt}

Base utilizada: \rule{4cm}{0.4pt}

Data de criação: \rule{3cm}{0.4pt}

Tamanho / Medidas base: \rule{4cm}{0.4pt}

\vspace{0.4cm}

\textbf{Observações técnicas}

\rule{\textwidth}{0.4pt}

\rule{\textwidth}{0.4pt}

\rule{\textwidth}{0.4pt}

\end{minipage}
&
\begin{minipage}[t]{0.43\textwidth}
\normalsize

\textbf{ID do Molde:} \rule{4cm}{0.5pt}

\vspace{0.4cm}

Tipo: \rule{5cm}{0.4pt}

Base utilizada: \rule{4cm}{0.4pt}

Data de criação: \rule
